### ISSUE TITLE
TAG border rendered too small at bottom

### ISSUE THREAD

**Issue by kimcs** [Cantara/visuale#150]
Browser used was Chrome on macOS.
Example from EntraOS devtest environment where rendering fails:
![image](https://user-images.githubusercontent.com/6402881/123228545-cd27eb00-d4d5-11eb-9b2c-b1bcc7bc2fba.png)

**Comment by appartiff** [comment]
This is related to an bug in the chrome engine and most other engines with flex-column: https://bugs.chromium.org/p/chromium/issues/detail?id=507397
Visuale is "hacked" around those browser engine limitations, but we have met on a halt where a rewrite of how Visuale calculate the dimensions is needed or Chrome sort out their bug which have been open since 2011.
